#!/usr/bin/env python3
"""Build a safe MTA overlay from the KotnikRP open.mp distribution.

The generated overlay intentionally contains only the gamemode AMX and its
model resource. It never copies config.json, database credentials, Discord
tokens, RCON data, or legacy SA-MP plugins.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import shutil
from dataclasses import dataclass
from pathlib import Path
from xml.sax.saxutils import escape


CHAR_MODEL = re.compile(
    r'AddCharModel\(\s*(-?\d+)\s*,\s*(-?\d+)\s*,\s*"([^"]+)"\s*,\s*"([^"]+)"\s*\)\s*;'
)
SIMPLE_MODEL = re.compile(
    r'AddSimpleModel\(\s*(-?\d+)\s*,\s*(-?\d+)\s*,\s*(-?\d+)\s*,\s*"([^"]+)"\s*,\s*"([^"]+)"\s*\)\s*;'
)
@dataclass(frozen=True)
class Model:
    kind: str
    base: int
    custom: int
    dff: str
    txd: str
    world: int = -1


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def parse_artconfig(path: Path) -> tuple[list[Model], list[dict[str, object]]]:
    models: dict[tuple[str, int], Model] = {}
    duplicates: list[dict[str, object]] = []
    for line_number, raw_line in enumerate(
        path.read_text(encoding="utf-8-sig").splitlines(), 1
    ):
        line = raw_line.split("//", 1)[0].strip()
        match = CHAR_MODEL.search(line)
        if match:
            base, custom, dff, txd = match.groups()
            model = Model("ped", int(base), int(custom), dff, txd)
        else:
            match = SIMPLE_MODEL.search(line)
            if not match:
                continue
            world, base, custom, dff, txd = match.groups()
            model = Model("object", int(base), int(custom), dff, txd, int(world))
        key = (model.kind, model.custom)
        previous = models.get(key)
        if previous:
            duplicates.append(
                {
                    "kind": model.kind,
                    "custom": model.custom,
                    "line": line_number,
                    "kept": previous.__dict__,
                    "ignored": model.__dict__,
                }
            )
            continue
        models[key] = model
    return list(models.values()), duplicates


def resolve_assets(
    models: list[Model], assets: Path
) -> tuple[list[Model], list[dict[str, str]], set[int]]:
    resolved = []
    repairs: list[dict[str, str]] = []
    fallback_peds: set[int] = set()
    for model in models:
        names = []
        unresolved = []
        for filename in (model.dff, model.txd):
            if (assets / filename).is_file():
                names.append(filename)
                continue
            suffix = filename.split("_", 1)[1] if "_" in filename else filename
            candidates = []
            if (assets / suffix).is_file():
                candidates = [assets / suffix]
            else:
                candidates = sorted(assets.glob(f"*_{suffix}"))
            if len(candidates) == 1:
                replacement = candidates[0].name
                repairs.append({"requested": filename, "replacement": replacement})
                names.append(replacement)
            else:
                unresolved.append(filename)
        if unresolved:
            if model.kind == "ped":
                fallback_peds.add(model.custom)
                resolved.append(model)
                repairs.append(
                    {
                        "requested": ", ".join(unresolved),
                        "replacement": f"stock ped {model.base}",
                    }
                )
                continue
            raise FileNotFoundError("Missing object assets: " + ", ".join(unresolved))
        resolved.append(
            Model(
                model.kind,
                model.base,
                model.custom,
                names[0],
                names[1],
                model.world,
            )
        )
    return resolved, repairs, fallback_peds


def write_registry(path: Path, models: list[Model], fallback_peds: set[int]) -> None:
    peds = sorted((model for model in models if model.kind == "ped"), key=lambda m: m.custom)
    objects = sorted(
        (model for model in models if model.kind == "object"), key=lambda m: m.custom
    )
    lines = [
        "-- Generated by mta/tools/build_kotnik_variant.py; do not edit.\n",
        "MRP_MODELS = {\n",
    ]
    for model in peds:
        if model.custom in fallback_peds:
            lines.append(
                f"    [{model.custom}] = {{ base = {model.base}, fallback = true }},\n"
            )
        else:
            lines.append(
                f'    [{model.custom}] = {{ base = {model.base}, '
                f'dff = "assets/{model.dff}", txd = "assets/{model.txd}" }},\n'
            )
    lines.extend(["}\n\n", "MRP_OBJECT_MODELS = {\n"])
    for model in objects:
        # open.mp accepts SA-MP object IDs as replacement bases. MTA does not;
        # the custom DFF replaces the transport model completely.
        base = model.base if 321 <= model.base <= 18630 else 1337
        lines.append(
            f'    [{model.custom}] = {{ base = {base}, '
            f'dff = "assets/{model.dff}", txd = "assets/{model.txd}", '
            f"world = {model.world} }},\n"
        )
    lines.append("}\n")
    path.write_text("".join(lines), encoding="utf-8")


def write_meta(path: Path, asset_names: list[str]) -> None:
    lines = [
        "<meta>\n",
        '    <info name="KotnikRP custom models" author="KotnikRP / OpenAI" version="0.1.0" />\n',
        '    <min_mta_version server="1.6.0-9.22457" client="1.6.0-9.22420" />\n',
        '    <script src="shared/registry.lua" type="shared" cache="false" />\n',
        '    <script src="shared/vc_objects.lua" type="shared" cache="false" />\n',
        '    <script src="server/main.lua" type="server" />\n',
        '    <script src="client/main.lua" type="client" cache="false" />\n',
        '    <export function="getBaseModel" type="server" />\n',
        '    <export function="getObjectBaseModel" type="server" />\n',
        '    <export function="registerObjectModel" type="server" />\n',
        '    <export function="applyObjectModel" type="client" />\n',
        '    <export function="applyObjectMaterial" type="client" />\n',
        '    <export function="createPreviewElement" type="client" />\n',
        '    <file src="client/material_replace.fx" />\n',
    ]
    for filename in asset_names:
        lines.append(f'    <file src="assets/{escape(filename)}" />\n')
    lines.append("</meta>\n")
    path.write_text("".join(lines), encoding="utf-8")


def build_overlay(
    source: Path, runtime: Path, output: Path, amx: Path | None = None
) -> None:
    artconfig = source / "KRP-V2-Modele/models/artconfig.txt"
    assets = artconfig.parent
    amx = amx or source / "gamemodes/Kotnik-RP-MTA.amx"
    scriptfiles = source / "scriptfiles"
    template = runtime / "mta/server/mods/deathmatch/resources/mrp_models"
    required = (
        artconfig,
        amx,
        scriptfiles,
        template / "client/main.lua",
        template / "server/main.lua",
    )
    missing_required = [str(path) for path in required if not path.exists()]
    if missing_required:
        raise FileNotFoundError("Missing input: " + ", ".join(missing_required))
    if output.exists() and any(output.iterdir()):
        raise FileExistsError(f"Output directory is not empty: {output}")

    models, duplicates = parse_artconfig(artconfig)
    models, asset_repairs, fallback_peds = resolve_assets(models, assets)

    resource = output / "mods/deathmatch/resources/mrp_models"
    amx_resource = output / "mods/deathmatch/resources/amx-kotnik"
    (resource / "shared").mkdir(parents=True, exist_ok=True)
    (resource / "assets").mkdir(parents=True, exist_ok=True)
    amx_resource.mkdir(parents=True, exist_ok=True)
    shutil.copytree(template / "client", resource / "client")
    shutil.copytree(template / "server", resource / "server")
    (resource / "shared/vc_objects.lua").write_text(
        "-- KotnikRP variant intentionally contains no Vice City catalog.\n",
        encoding="utf-8",
    )
    write_registry(resource / "shared/registry.lua", models, fallback_peds)

    asset_names = sorted(
        {
            name
            for model in models
            if model.custom not in fallback_peds
            for name in (model.dff, model.txd)
        },
        key=str.casefold,
    )
    for filename in asset_names:
        shutil.copy2(assets / filename, resource / "assets" / filename)
    write_meta(resource / "meta.xml", asset_names)

    (amx_resource / "meta.xml").write_text(
        "<meta>\n"
        '    <info type="map" gamemodes="amx" name="KotnikRP test" '
        'author="KotnikRP" />\n'
        '    <amx src="Kotnik-RP-MTA.amx" />\n'
        "</meta>\n",
        encoding="utf-8",
    )
    shutil.copy2(amx, amx_resource / "Kotnik-RP-MTA.amx")
    shutil.copytree(scriptfiles, amx_resource / "scriptfiles")

    report = {
        "schema_version": 1,
        "source": source.name,
        "status": "compatibility-audit-required",
        "gamemode": "Kotnik-RP-MTA.amx",
        "gamemode_size": (amx_resource / "Kotnik-RP-MTA.amx").stat().st_size,
        "gamemode_sha256": sha256(amx_resource / "Kotnik-RP-MTA.amx"),
        "scriptfiles": sum(path.is_file() for path in scriptfiles.rglob("*")),
        "scriptfiles_bytes": sum(
            path.stat().st_size for path in scriptfiles.rglob("*") if path.is_file()
        ),
        "ped_models": sum(model.kind == "ped" for model in models),
        "object_models": sum(model.kind == "object" for model in models),
        "asset_files": len(asset_names),
        "asset_bytes": sum((resource / "assets" / name).stat().st_size for name in asset_names),
        "duplicates": duplicates,
        "asset_repairs": asset_repairs,
        "fallback_peds": sorted(fallback_peds),
        "vice_city_catalog": False,
    }
    (output / "VARIANT.json").write_text(
        json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    (output / "README-INSTALL.txt").write_text(
        "KotnikRP MTA evaluation overlay\n"
        "================================\n"
        "DO NOT INSTALL THIS OVERLAY ON THE RUNNING SERVER.\n"
        "It contains the MTA-adapted Kotnik-RP-MTA.amx and model assets for isolated tests,\n"
        "but the AMX still requires a compatibility audit and plugin fallbacks.\n"
        "The production amx-mrucznik resource is intentionally not included.\n"
        "Verify MANIFEST.sha256 before every isolated test.\n",
        encoding="utf-8",
    )
    # Write the checksum list last so it also protects the installation notes
    # and the machine-readable variant report.
    files = sorted(path for path in output.rglob("*") if path.is_file())
    manifest_lines = [
        f"{sha256(path)}  {path.relative_to(output).as_posix()}\n" for path in files
    ]
    (output / "MANIFEST.sha256").write_text("".join(manifest_lines), encoding="utf-8")
    print(
        f"Built KotnikRP overlay: {report['ped_models']} peds, "
        f"{report['object_models']} objects, {report['asset_files']} assets"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument(
        "--runtime", type=Path, default=Path(__file__).resolve().parents[2]
    )
    parser.add_argument(
        "--amx",
        type=Path,
        help="Compiled Kotnik-RP-MTA.amx (defaults to SOURCE/gamemodes/Kotnik-RP-MTA.amx)",
    )
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    build_overlay(
        args.source.resolve(),
        args.runtime.resolve(),
        args.output.resolve(),
        args.amx.resolve() if args.amx else None,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
