#!/usr/bin/env python3
"""Build the shared MTA object registry from Mrucznik's Vice City IDE table."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


ENTRY = re.compile(
    r'^\s*\{\s*(-?\d+)\s*,\s*!"([^"]+)"\s*,\s*!"([^"]+)"'
    r'(?:\s*,\s*(\d+)\s*,\s*(\d+))?\s*\}',
    re.MULTILINE,
)

# vicecity_callbacks.pwn deliberately excludes ordinary LOD definitions; these
# are never registered or streamed.  A small set is explicitly retained by the
# original gamemode because it is used as ordinary geometry.
ALLOWED_LOD_MODELS = {
    -9150, -9151, -9152, -9153, -9888, -9887, -9893, -9889, -9892,
    -9894, -9261, -9262, -9207, -9175, -9176, -9177, -9263,
}

# The distributed vc4samp archive uses these two GTA United texture-dictionary
# names, while the Pawn IDE table refers to their older Vice City names.  The
# expected material names are present in the replacement dictionaries
# (freight: frate_*/midgrey64; docks rail: rail1/rail1_a), so this is a naming
# repair rather than a visual/model substitution.
TEXTURE_ALIASES = {
    "docks.txd": "docksvc.txd",
    "subcrates.txd": "subcratesvc.txd",
}


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--assets", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    source = args.source.read_text(encoding="cp1250", errors="strict")
    models: dict[int, tuple[str, str, int | None, int | None]] = {}
    missing: dict[int, tuple[str, str]] = {}
    aliased_textures: dict[str, str] = {}
    entries = 0
    registered_entries = 0

    for match in ENTRY.finditer(source):
        entries += 1
        model = int(match.group(1))
        dff = match.group(2)
        txd = match.group(3)
        time_on = int(match.group(4)) if match.group(4) else None
        time_off = int(match.group(5)) if match.group(5) else None
        if time_on is None and "lod" in dff.lower() and model not in ALLOWED_LOD_MODELS:
            continue
        registered_entries += 1
        dff_path = args.assets / "dff" / dff
        txd_path = args.assets / "txd" / txd
        if not txd_path.is_file() and txd in TEXTURE_ALIASES:
            alias = TEXTURE_ALIASES[txd]
            alias_path = args.assets / "txd" / alias
            if alias_path.is_file():
                aliased_textures[txd] = alias
                txd = alias
                txd_path = alias_path
        if not dff_path.is_file() or not txd_path.is_file():
            missing[model] = (dff if not dff_path.is_file() else "", txd if not txd_path.is_file() else "")
            continue
        # Match AddSimpleModel semantics: the last loadable definition wins,
        # while a later broken duplicate must not replace an earlier valid one.
        models[model] = (dff, txd, time_on, time_off)
        missing.pop(model, None)

    lines = [
        "-- Generated by mta/tools/build_vc_model_catalog.py; do not edit.",
        "MRP_OBJECT_MODELS = MRP_OBJECT_MODELS or {}",
    ]
    for model in sorted(models):
        dff, txd, time_on, time_off = models[model]
        timed = ""
        if time_on is not None:
            timed = f", timeOn = {time_on}, timeOff = {time_off}"
        lines.append(
            f'    MRP_OBJECT_MODELS[{model}] = {{ base = 1337, '
            f'dff = "assets/vc4samp/dff/{dff}", '
            f'txd = "assets/vc4samp/txd/{txd}", world = -1{timed} }}'
        )

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(
        f"Parsed {entries} IDE entries; {registered_entries} are registered by Pawn; "
        f"wrote {len(models)} loadable Vice City models"
    )
    for original, alias in sorted(aliased_textures.items()):
        print(f"Texture alias: {original} -> {alias}")
    if missing:
        print(f"Missing {len(missing)} final model definitions:")
        for model, (dff, txd) in sorted(missing.items()):
            absent = ", ".join(name for name in (dff, txd) if name)
            print(f"  {model}: {absent}")


if __name__ == "__main__":
    main()
