#!/usr/bin/env python3
"""Generate MTA custom-ped registry from SA-MP 0.3.DL artconfig."""

from __future__ import annotations

import argparse
import json
import re
import tarfile
from pathlib import Path


MODEL_RE = re.compile(
    r'^\s*AddCharModel\(\s*(-?\d+)\s*,\s*(-?\d+)\s*,\s*"([^"]+)"\s*,\s*"([^"]+)"\s*\)\s*;',
    re.MULTILINE,
)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo", type=Path, default=Path(__file__).resolve().parents[2])
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).resolve().parents[1]
        / "server/mods/deathmatch/resources/mrp_models/shared/registry.lua",
    )
    args = parser.parse_args()
    repo = args.repo.resolve()
    source = repo / "gamemodes/modules/03DL/artconfig.txt"
    archive = repo / "serverfiles.tar.gz"
    text = source.read_bytes().decode("cp1250")
    models = [
        {"base": int(base), "custom": int(custom), "dff": dff, "txd": txd}
        for base, custom, dff, txd in MODEL_RE.findall(text)
    ]
    if len({model["custom"] for model in models}) != len(models):
        raise ValueError("Duplicate custom model ID in artconfig.txt")

    if archive.exists() and archive.stat().st_size > 1024:
        with tarfile.open(archive, "r:gz") as handle:
            names = {member.name for member in handle.getmembers()}
        missing = [
            asset
            for model in models
            for asset in (model["dff"], model["txd"])
            if f"serverfiles/models/{asset}" not in names
        ]
        if missing:
            raise FileNotFoundError("Missing 0.3.DL assets: " + ", ".join(sorted(set(missing))))

    args.output.parent.mkdir(parents=True, exist_ok=True)
    lines = ["-- Generated by mta/tools/build_model_catalog.py; do not edit.\n", "MRP_MODELS = {\n"]
    for model in models:
        lines.append(
            f'    [{model["custom"]}] = {{ base = {model["base"]}, dff = "assets/{model["dff"]}", txd = "assets/{model["txd"]}" }},\n'
        )
    lines.append("}\n")
    args.output.write_text("".join(lines), encoding="utf-8")

    report = Path(__file__).resolve().parents[1] / "compatibility/models.json"
    report.parent.mkdir(parents=True, exist_ok=True)
    report.write_text(
        json.dumps({"schema_version": 1, "model_count": len(models), "models": models}, indent=2) + "\n",
        encoding="utf-8",
    )
    print(f"Generated {len(models)} custom ped models")


if __name__ == "__main__":
    main()
