#!/usr/bin/env python3
"""Import the Kotnik SA-MP 0.3.DL model catalog into mrp_models."""

from __future__ import annotations

import argparse
import re
import shutil
from dataclasses import dataclass
from pathlib import Path


CHAR_RE = re.compile(
    r'^\s*AddCharModel\(\s*(-?\d+)\s*,\s*(-?\d+)\s*,\s*"([^"]+)"\s*,\s*"([^"]+)"\s*\)\s*;',
    re.MULTILINE,
)
OBJECT_RE = re.compile(
    r'^\s*AddSimpleModel\(\s*(-?\d+)\s*,\s*(-?\d+)\s*,\s*(-?\d+)\s*,\s*"([^"]+)"\s*,\s*"([^"]+)"\s*\)\s*;',
    re.MULTILINE,
)


@dataclass(frozen=True)
class Model:
    kind: str
    world: int
    base: int
    custom: int
    dff: str
    txd: str


def read_artconfig(path: Path) -> str:
    raw = path.read_bytes()
    for encoding in ("utf-8-sig", "cp1250", "latin1"):
        try:
            return raw.decode(encoding)
        except UnicodeDecodeError:
            pass
    raise UnicodeError(f"Nie można odczytać {path}")


def parse_models(text: str) -> list[Model]:
    parsed: list[Model] = []
    parsed.extend(
        Model("ped", -1, int(base), int(custom), dff, txd)
        for base, custom, dff, txd in CHAR_RE.findall(text)
    )
    parsed.extend(
        Model("object", int(world), int(base), int(custom), dff, txd)
        for world, base, custom, dff, txd in OBJECT_RE.findall(text)
    )

    # SA-MP keeps the first successfully registered custom ID.  The supplied
    # artconfig contains three later duplicate skin IDs, so mirror that rule.
    unique: list[Model] = []
    seen: set[tuple[str, int]] = set()
    for model in parsed:
        key = model.kind, model.custom
        if key not in seen:
            unique.append(model)
            seen.add(key)
    return unique


def lua_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--resource", type=Path, required=True)
    parser.add_argument(
        "--catalog-only",
        action="store_true",
        help="Generate shared/kotnik_models.lua without copying assets.",
    )
    args = parser.parse_args()

    source = args.source.resolve()
    resource = args.resource.resolve()
    artconfig = source / "artconfig.txt"
    if not artconfig.is_file():
        raise FileNotFoundError(f"Brak katalogu modeli Kotnika: {artconfig}")

    files = {
        child.name.casefold(): child
        for child in source.iterdir()
        if child.is_file()
    }
    models = parse_models(read_artconfig(artconfig))
    valid: list[Model] = []
    missing: list[str] = []
    for model in models:
        absent = [name for name in (model.dff, model.txd) if name.casefold() not in files]
        if absent:
            missing.append(f"{model.kind} {model.custom}: {', '.join(absent)}")
        else:
            valid.append(model)

    asset_dir = resource / "assets" / "kotnik"
    if not args.catalog_only:
        asset_dir.mkdir(parents=True, exist_ok=True)
        required = {
            name.casefold()
            for model in valid
            for name in (model.dff, model.txd)
        }
        for name in sorted(required):
            shutil.copy2(files[name], asset_dir / files[name].name)
        # A matching standalone COL is optional.  Copy it when supplied.
        for model in valid:
            col = Path(model.dff).with_suffix(".col").name.casefold()
            if col in files:
                shutil.copy2(files[col], asset_dir / files[col].name)

    output = resource / "shared" / "kotnik_models.lua"
    output.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "-- Generated by mta/tools/import_kotnik_models.py; do not edit.\n",
        "-- Kotnik definitions intentionally override the old Mrucznik catalog.\n",
        "MRP_MODELS = MRP_MODELS or {}\n",
        "MRP_OBJECT_MODELS = MRP_OBJECT_MODELS or {}\n\n",
    ]
    for model in valid:
        dff = f"assets/kotnik/{lua_string(files[model.dff.casefold()].name)}"
        txd = f"assets/kotnik/{lua_string(files[model.txd.casefold()].name)}"
        if model.kind == "ped":
            lines.append(
                f' MRP_MODELS[{model.custom}] = {{ base = {model.base}, dff = "{dff}", txd = "{txd}" }}\n'
            )
            continue
        col_name = Path(model.dff).with_suffix(".col").name.casefold()
        col = (
            f', col = "assets/kotnik/{lua_string(files[col_name].name)}"'
            if col_name in files
            else ""
        )
        lines.append(
            f' MRP_OBJECT_MODELS[{model.custom}] = {{ base = {model.base}, dff = "{dff}", '
            f'txd = "{txd}"{col}, world = {model.world} }}\n'
        )
    output.write_text("".join(lines), encoding="utf-8", newline="\n")

    ped_count = sum(model.kind == "ped" for model in valid)
    object_count = sum(model.kind == "object" for model in valid)
    print(f"Kotnik: {ped_count} skinów, {object_count} obiektów, {len(missing)} pominiętych wpisów")
    for entry in missing:
        print(f"UWAGA: brak pliku dla {entry}")


if __name__ == "__main__":
    main()
