-- Generated by mta/tools/import_kotnik_models.py; do not edit.
-- Kotnik definitions intentionally override the old Mrucznik catalog.
MRP_MODELS = MRP_MODELS or {}
MRP_OBJECT_MODELS = MRP_OBJECT_MODELS or {}

 MRP_MODELS[20001] = { base = 154, dff = "assets/kotnik/skin20001.dff", txd = "assets/kotnik/skin20001.txd" }
 MRP_MODELS[20003] = { base = 154, dff = "assets/kotnik/skin20003.dff", txd = "assets/kotnik/skin20003.txd" }
 MRP_MODELS[20005] = { base = 154, dff = "assets/kotnik/skin20005.dff", txd = "assets/kotnik/skin20005.txd" }
 MRP_MODELS[20006] = { base = 154, dff = "assets/kotnik/skin20006.dff", txd = "assets/kotnik/skin20006.txd" }
 MRP_MODELS[20009] = { base = 154, dff = "assets/kotnik/skin20009.dff", txd = "assets/kotnik/skin20009.txd" }
 MRP_MODELS[20010] = { base = 154, dff = "assets/kotnik/skin20010.dff", txd = "assets/kotnik/skin20010.txd" }
 MRP_MODELS[20013] = { base = 154, dff = "assets/kotnik/skin20013.dff", txd = "assets/kotnik/skin20013.txd" }
 MRP_MODELS[20014] = { base = 154, dff = "assets/kotnik/skin20014.dff", txd = "assets/kotnik/skin20014.txd" }
 MRP_MODELS[20015] = { base = 154, dff = "assets/kotnik/skin20015.dff", txd = "assets/kotnik/skin20015.txd" }
 MRP_MODELS[20016] = { base = 154, dff = "assets/kotnik/skin20016.dff", txd = "assets/kotnik/skin20016.txd" }
 MRP_MODELS[20017] = { base = 154, dff = "assets/kotnik/skin20017.dff", txd = "assets/kotnik/skin20017.txd" }
 MRP_MODELS[20019] = { base = 154, dff = "assets/kotnik/skin20019.dff", txd = "assets/kotnik/skin20019.txd" }
 MRP_MODELS[20020] = { base = 154, dff = "assets/kotnik/skin20020.dff", txd = "assets/kotnik/skin20020.txd" }
 MRP_MODELS[20021] = { base = 154, dff = "assets/kotnik/skin_20021.dff", txd = "assets/kotnik/skin_20021.txd" }
 MRP_MODELS[20002] = { base = 154, dff = "assets/kotnik/skin20002.dff", txd = "assets/kotnik/skin20002.txd" }
 MRP_MODELS[20004] = { base = 154, dff = "assets/kotnik/skin20004.dff", txd = "assets/kotnik/skin20004.txd" }
 MRP_MODELS[20012] = { base = 154, dff = "assets/kotnik/skin20012.dff", txd = "assets/kotnik/skin20012.txd" }
 MRP_MODELS[20011] = { base = 154, dff = "assets/kotnik/skin20011.dff", txd = "assets/kotnik/skin20011.txd" }
 MRP_MODELS[20018] = { base = 154, dff = "assets/kotnik/skin20018.dff", txd = "assets/kotnik/skin20018.txd" }
 MRP_MODELS[20007] = { base = 154, dff = "assets/kotnik/skin20007.dff", txd = "assets/kotnik/skin20007.txd" }
 MRP_MODELS[20008] = { base = 154, dff = "assets/kotnik/skin20008.dff", txd = "assets/kotnik/skin20008.txd" }
 MRP_MODELS[21001] = { base = 55, dff = "assets/kotnik/skin21001.dff", txd = "assets/kotnik/skin21001.txd" }
 MRP_MODELS[21002] = { base = 55, dff = "assets/kotnik/skin21002.dff", txd = "assets/kotnik/skin21002.txd" }
 MRP_MODELS[21003] = { base = 55, dff = "assets/kotnik/skin21003.dff", txd = "assets/kotnik/skin21003.txd" }
 MRP_MODELS[21004] = { base = 55, dff = "assets/kotnik/skin21004.dff", txd = "assets/kotnik/skin21004.txd" }
 MRP_MODELS[21005] = { base = 55, dff = "assets/kotnik/skin21005.dff", txd = "assets/kotnik/skin21005.txd" }
 MRP_MODELS[21006] = { base = 55, dff = "assets/kotnik/skin21006.dff", txd = "assets/kotnik/skin21006.txd" }
 MRP_MODELS[21007] = { base = 55, dff = "assets/kotnik/skin21007.dff", txd = "assets/kotnik/skin21007.txd" }
 MRP_MODELS[21008] = { base = 55, dff = "assets/kotnik/skin21008.dff", txd = "assets/kotnik/skin21008.txd" }
 MRP_MODELS[21009] = { base = 55, dff = "assets/kotnik/skin21009.dff", txd = "assets/kotnik/skin21009.txd" }
 MRP_MODELS[21010] = { base = 55, dff = "assets/kotnik/skin21010.dff", txd = "assets/kotnik/skin21010.txd" }
 MRP_MODELS[21011] = { base = 55, dff = "assets/kotnik/skin21011.dff", txd = "assets/kotnik/skin21011.txd" }
 MRP_MODELS[21012] = { base = 55, dff = "assets/kotnik/skin21012.dff", txd = "assets/kotnik/skin21012.txd" }
 MRP_MODELS[21013] = { base = 233, dff = "assets/kotnik/21013_bfyri.dff", txd = "assets/kotnik/21013_bfyri.txd" }
 MRP_MODELS[21014] = { base = 233, dff = "assets/kotnik/21014_bfyst.dff", txd = "assets/kotnik/21014_bfyst.txd" }
 MRP_MODELS[21015] = { base = 233, dff = "assets/kotnik/21015_cat.dff", txd = "assets/kotnik/21015_cat.txd" }
 MRP_MODELS[21016] = { base = 233, dff = "assets/kotnik/21016_flowers.dff", txd = "assets/kotnik/21016_flowers.txd" }
 MRP_MODELS[21017] = { base = 233, dff = "assets/kotnik/21017_gangrl3.dff", txd = "assets/kotnik/21017_gangrl3.txd" }
 MRP_MODELS[21018] = { base = 233, dff = "assets/kotnik/21018_hfyri.dff", txd = "assets/kotnik/21018_hfyri.txd" }
 MRP_MODELS[21019] = { base = 233, dff = "assets/kotnik/21019_kendl1.dff", txd = "assets/kotnik/21019_kendl1.txd" }
 MRP_MODELS[21020] = { base = 233, dff = "assets/kotnik/21020_kendl2.dff", txd = "assets/kotnik/21020_kendl2.txd" }
 MRP_MODELS[21021] = { base = 233, dff = "assets/kotnik/21021_kendl3.dff", txd = "assets/kotnik/21021_kendl3.txd" }
 MRP_MODELS[21022] = { base = 233, dff = "assets/kotnik/21022_kendl4.dff", txd = "assets/kotnik/21022_kendl4.txd" }
 MRP_MODELS[21023] = { base = 233, dff = "assets/kotnik/21023_kendl5.dff", txd = "assets/kotnik/21023_kendl5.txd" }
 MRP_MODELS[21024] = { base = 233, dff = "assets/kotnik/21024_kendl6.dff", txd = "assets/kotnik/21024_kendl6.txd" }
 MRP_MODELS[21025] = { base = 233, dff = "assets/kotnik/21025_lady.dff", txd = "assets/kotnik/21025_lady.txd" }
 MRP_MODELS[21026] = { base = 233, dff = "assets/kotnik/21026_mecgrl3.dff", txd = "assets/kotnik/21026_mecgrl3.txd" }
 MRP_MODELS[21027] = { base = 233, dff = "assets/kotnik/21027_nurgrl3.dff", txd = "assets/kotnik/21027_nurgrl3.txd" }
 MRP_MODELS[21028] = { base = 233, dff = "assets/kotnik/21028_ofyst.dff", txd = "assets/kotnik/21028_ofyst.txd" }
 MRP_MODELS[21029] = { base = 233, dff = "assets/kotnik/21029_ofyst1.dff", txd = "assets/kotnik/21029_ofyst1.txd" }
 MRP_MODELS[21030] = { base = 233, dff = "assets/kotnik/21030_ofyst2.dff", txd = "assets/kotnik/21030_ofyst2.txd" }
 MRP_MODELS[21031] = { base = 233, dff = "assets/kotnik/21031_persn1.dff", txd = "assets/kotnik/21031_persn1.txd" }
 MRP_MODELS[21032] = { base = 233, dff = "assets/kotnik/21032_raiders.dff", txd = "assets/kotnik/21032_raiders.txd" }
 MRP_MODELS[21033] = { base = 233, dff = "assets/kotnik/21033_skinismi.dff", txd = "assets/kotnik/21033_skinismi.txd" }
 MRP_MODELS[21034] = { base = 233, dff = "assets/kotnik/21034_sofybu.dff", txd = "assets/kotnik/21034_sofybu.txd" }
 MRP_MODELS[21035] = { base = 233, dff = "assets/kotnik/21035_sofyst.dff", txd = "assets/kotnik/21035_sofyst.txd" }
 MRP_MODELS[21036] = { base = 233, dff = "assets/kotnik/21036_sofyst1.dff", txd = "assets/kotnik/21036_sofyst1.txd" }
 MRP_MODELS[21037] = { base = 233, dff = "assets/kotnik/21037_sofyst2.dff", txd = "assets/kotnik/21037_sofyst2.txd" }
 MRP_MODELS[21038] = { base = 233, dff = "assets/kotnik/21038_swfyri1.dff", txd = "assets/kotnik/21038_swfyri1.txd" }
 MRP_MODELS[21039] = { base = 233, dff = "assets/kotnik/21039_swfyri3.dff", txd = "assets/kotnik/21039_swfyri3.txd" }
 MRP_MODELS[21040] = { base = 233, dff = "assets/kotnik/21040_swfyst2.dff", txd = "assets/kotnik/21040_swfyst2.txd" }
 MRP_MODELS[21041] = { base = 233, dff = "assets/kotnik/21041_swfyst3.dff", txd = "assets/kotnik/21041_swfyst3.txd" }
 MRP_MODELS[21042] = { base = 233, dff = "assets/kotnik/21042_vwfypro1.dff", txd = "assets/kotnik/21042_vwfypro1.txd" }
 MRP_MODELS[21043] = { base = 233, dff = "assets/kotnik/21043_vwfypro2.dff", txd = "assets/kotnik/21043_vwfypro2.txd" }
 MRP_MODELS[21044] = { base = 233, dff = "assets/kotnik/21044_vwfypro3.dff", txd = "assets/kotnik/21044_vwfypro3.txd" }
 MRP_MODELS[21045] = { base = 233, dff = "assets/kotnik/21045_vwfywa2.dff", txd = "assets/kotnik/21045_vwfywa2.txd" }
 MRP_MODELS[21046] = { base = 233, dff = "assets/kotnik/21046_wfybu1.dff", txd = "assets/kotnik/21046_wfybu1.txd" }
 MRP_MODELS[21047] = { base = 233, dff = "assets/kotnik/21047_wfybu2.dff", txd = "assets/kotnik/21047_wfybu2.txd" }
 MRP_MODELS[21048] = { base = 233, dff = "assets/kotnik/21048_wfyclot.dff", txd = "assets/kotnik/21048_wfyclot.txd" }
 MRP_MODELS[21049] = { base = 233, dff = "assets/kotnik/21049_wfyclot1.dff", txd = "assets/kotnik/21049_wfyclot1.txd" }
 MRP_MODELS[21050] = { base = 233, dff = "assets/kotnik/21050_wfyclot2.dff", txd = "assets/kotnik/21050_wfyclot2.txd" }
 MRP_MODELS[21051] = { base = 233, dff = "assets/kotnik/21051_wfyclot3.dff", txd = "assets/kotnik/21051_wfyclot3.txd" }
 MRP_MODELS[21052] = { base = 233, dff = "assets/kotnik/21052_wfyri1.dff", txd = "assets/kotnik/21052_wfyri1.txd" }
 MRP_MODELS[21053] = { base = 233, dff = "assets/kotnik/21053_wfyri2.dff", txd = "assets/kotnik/21053_wfyri2.txd" }
 MRP_MODELS[21054] = { base = 233, dff = "assets/kotnik/21054_wfyri4.dff", txd = "assets/kotnik/21054_wfyri4.txd" }
 MRP_MODELS[21055] = { base = 233, dff = "assets/kotnik/21055_wfyri5.dff", txd = "assets/kotnik/21055_wfyri5.txd" }
 MRP_MODELS[21056] = { base = 233, dff = "assets/kotnik/21056_wfyri6.dff", txd = "assets/kotnik/21056_wfyri6.txd" }
 MRP_MODELS[21057] = { base = 233, dff = "assets/kotnik/21057_wfyst1.dff", txd = "assets/kotnik/21057_wfyst1.txd" }
 MRP_MODELS[21058] = { base = 233, dff = "assets/kotnik/21058_wfyst10.dff", txd = "assets/kotnik/21058_wfyst10.txd" }
 MRP_MODELS[21059] = { base = 233, dff = "assets/kotnik/21059_wfyst11.dff", txd = "assets/kotnik/21059_wfyst11.txd" }
 MRP_MODELS[21060] = { base = 233, dff = "assets/kotnik/21060_wfyst12.dff", txd = "assets/kotnik/21060_wfyst12.txd" }
 MRP_MODELS[21061] = { base = 233, dff = "assets/kotnik/21061_wfyst13.dff", txd = "assets/kotnik/21061_wfyst13.txd" }
 MRP_MODELS[21062] = { base = 233, dff = "assets/kotnik/21062_wfyst14.dff", txd = "assets/kotnik/21062_wfyst14.txd" }
 MRP_MODELS[21063] = { base = 233, dff = "assets/kotnik/21063_wfyst15.dff", txd = "assets/kotnik/21063_wfyst15.txd" }
 MRP_MODELS[21064] = { base = 233, dff = "assets/kotnik/21064_wfyst16.dff", txd = "assets/kotnik/21064_wfyst16.txd" }
 MRP_MODELS[21065] = { base = 233, dff = "assets/kotnik/21065_wfyst3.dff", txd = "assets/kotnik/21065_wfyst3.txd" }
 MRP_MODELS[21066] = { base = 233, dff = "assets/kotnik/21066_wfyst4.dff", txd = "assets/kotnik/21066_wfyst4.txd" }
 MRP_MODELS[21067] = { base = 233, dff = "assets/kotnik/21067_wfyst5.dff", txd = "assets/kotnik/21067_wfyst5.txd" }
 MRP_MODELS[21068] = { base = 233, dff = "assets/kotnik/21068_wfyst6.dff", txd = "assets/kotnik/21068_wfyst6.txd" }
 MRP_MODELS[21069] = { base = 233, dff = "assets/kotnik/21069_wfyst7.dff", txd = "assets/kotnik/21069_wfyst7.txd" }
 MRP_MODELS[21070] = { base = 233, dff = "assets/kotnik/21070_wfyst8.dff", txd = "assets/kotnik/21070_wfyst8.txd" }
 MRP_MODELS[21071] = { base = 233, dff = "assets/kotnik/21071_wfyst9.dff", txd = "assets/kotnik/21071_wfyst9.txd" }
 MRP_MODELS[22001] = { base = 154, dff = "assets/kotnik/skin22001.dff", txd = "assets/kotnik/skin22001.txd" }
 MRP_MODELS[22002] = { base = 154, dff = "assets/kotnik/skin22002.dff", txd = "assets/kotnik/skin22002.txd" }
 MRP_MODELS[22004] = { base = 154, dff = "assets/kotnik/skin22004.dff", txd = "assets/kotnik/skin22004.txd" }
 MRP_MODELS[22008] = { base = 154, dff = "assets/kotnik/santa.dff", txd = "assets/kotnik/santa.txd" }
 MRP_MODELS[27001] = { base = 274, dff = "assets/kotnik/bmyff.dff", txd = "assets/kotnik/bmyff.txd" }
 MRP_MODELS[27002] = { base = 274, dff = "assets/kotnik/bmyffl.dff", txd = "assets/kotnik/bmyffl.txd" }
 MRP_MODELS[27003] = { base = 274, dff = "assets/kotnik/bmyffp.dff", txd = "assets/kotnik/bmyffp.txd" }
 MRP_MODELS[27004] = { base = 233, dff = "assets/kotnik/wfyff.dff", txd = "assets/kotnik/wfyff.txd" }
 MRP_MODELS[27005] = { base = 233, dff = "assets/kotnik/wfyffl.dff", txd = "assets/kotnik/wfyffl.txd" }
 MRP_MODELS[27006] = { base = 233, dff = "assets/kotnik/wfyffp.dff", txd = "assets/kotnik/wfyffp.txd" }
 MRP_MODELS[27007] = { base = 276, dff = "assets/kotnik/wmyff.dff", txd = "assets/kotnik/wmyff.txd" }
 MRP_MODELS[27008] = { base = 276, dff = "assets/kotnik/wmyffl.dff", txd = "assets/kotnik/wmyffl.txd" }
 MRP_MODELS[27009] = { base = 276, dff = "assets/kotnik/wmyffp.dff", txd = "assets/kotnik/wmyff.txd" }
 MRP_MODELS[27010] = { base = 280, dff = "assets/kotnik/skin27010.dff", txd = "assets/kotnik/skin27010.txd" }
 MRP_MODELS[27011] = { base = 280, dff = "assets/kotnik/skin27011.dff", txd = "assets/kotnik/skin27011.txd" }
 MRP_MODELS[27012] = { base = 280, dff = "assets/kotnik/skin27012.dff", txd = "assets/kotnik/skin27012.txd" }
 MRP_MODELS[27013] = { base = 280, dff = "assets/kotnik/skin27013.dff", txd = "assets/kotnik/skin27013.txd" }
 MRP_MODELS[27014] = { base = 280, dff = "assets/kotnik/skin27014.dff", txd = "assets/kotnik/skin27014.txd" }
 MRP_MODELS[27015] = { base = 233, dff = "assets/kotnik/skin27015.dff", txd = "assets/kotnik/skin27015.txd" }
 MRP_MODELS[27016] = { base = 233, dff = "assets/kotnik/skin27016.dff", txd = "assets/kotnik/skin27016.txd" }
 MRP_MODELS[27017] = { base = 233, dff = "assets/kotnik/skin27017.dff", txd = "assets/kotnik/skin27017.txd" }
 MRP_MODELS[27018] = { base = 233, dff = "assets/kotnik/skin27018.dff", txd = "assets/kotnik/skin27018.txd" }
 MRP_MODELS[27019] = { base = 280, dff = "assets/kotnik/GNDBIALAS.dff", txd = "assets/kotnik/GNDBIALAS.txd" }
 MRP_MODELS[27020] = { base = 280, dff = "assets/kotnik/GNDBIALASLYSY.dff", txd = "assets/kotnik/GNDBIALASLYSY.txd" }
 MRP_MODELS[27021] = { base = 280, dff = "assets/kotnik/GNDCZARNUCH.dff", txd = "assets/kotnik/GNDCZARNUCH.txd" }
 MRP_MODELS[27022] = { base = 280, dff = "assets/kotnik/GNDlatynos.dff", txd = "assets/kotnik/GNDlatynos.txd" }
 MRP_MODELS[27023] = { base = 233, dff = "assets/kotnik/GNDLASKA.dff", txd = "assets/kotnik/GNDLASKA.txd" }
 MRP_MODELS[27024] = { base = 233, dff = "assets/kotnik/skin27024.dff", txd = "assets/kotnik/skin27024.txd" }
 MRP_MODELS[27025] = { base = 280, dff = "assets/kotnik/skin27025.dff", txd = "assets/kotnik/skin27025.txd" }
 MRP_MODELS[27026] = { base = 233, dff = "assets/kotnik/skin27026.dff", txd = "assets/kotnik/skin27026.txd" }
 MRP_MODELS[27027] = { base = 280, dff = "assets/kotnik/skin27027.dff", txd = "assets/kotnik/skin27027.txd" }
 MRP_MODELS[27028] = { base = 233, dff = "assets/kotnik/skin27028.dff", txd = "assets/kotnik/skin27028.txd" }
 MRP_MODELS[27030] = { base = 102, dff = "assets/kotnik/ballas1.dff", txd = "assets/kotnik/ballas1.txd" }
 MRP_MODELS[27031] = { base = 102, dff = "assets/kotnik/ballas2.dff", txd = "assets/kotnik/ballas2.txd" }
 MRP_MODELS[27032] = { base = 102, dff = "assets/kotnik/ballas3.dff", txd = "assets/kotnik/ballas3.txd" }
 MRP_MODELS[27033] = { base = 102, dff = "assets/kotnik/bmocd.dff", txd = "assets/kotnik/bmocd.txd" }
 MRP_MODELS[27034] = { base = 102, dff = "assets/kotnik/bmycr.dff", txd = "assets/kotnik/bmycr.txd" }
 MRP_MODELS[27035] = { base = 102, dff = "assets/kotnik/bmydrug.dff", txd = "assets/kotnik/bmydrug.txd" }
 MRP_MODELS[27036] = { base = 102, dff = "assets/kotnik/ballas1.dff", txd = "assets/kotnik/ballas1.txd" }
 MRP_MODELS[27037] = { base = 102, dff = "assets/kotnik/vbmocd.dff", txd = "assets/kotnik/vbmocd.txd" }
 MRP_MODELS[27038] = { base = 102, dff = "assets/kotnik/vbmyelv.dff", txd = "assets/kotnik/vbmyelv.txd" }
 MRP_MODELS[27039] = { base = 102, dff = "assets/kotnik/vhmyelv.dff", txd = "assets/kotnik/vhmyelv.txd" }
 MRP_MODELS[27040] = { base = 102, dff = "assets/kotnik/vimyelv.dff", txd = "assets/kotnik/vimyelv.txd" }
 MRP_MODELS[27041] = { base = 102, dff = "assets/kotnik/2.dff", txd = "assets/kotnik/2.txd" }
 MRP_MODELS[27042] = { base = 102, dff = "assets/kotnik/3.dff", txd = "assets/kotnik/3.txd" }
 MRP_MODELS[27043] = { base = 102, dff = "assets/kotnik/4.dff", txd = "assets/kotnik/4.txd" }
 MRP_MODELS[27044] = { base = 102, dff = "assets/kotnik/5.dff", txd = "assets/kotnik/5.txd" }
 MRP_MODELS[27045] = { base = 102, dff = "assets/kotnik/6.dff", txd = "assets/kotnik/6.txd" }
 MRP_MODELS[27046] = { base = 288, dff = "assets/kotnik/27046_bmybdu.dff", txd = "assets/kotnik/27046_bmybdu.txd" }
 MRP_MODELS[27047] = { base = 288, dff = "assets/kotnik/27047_bmysher.dff", txd = "assets/kotnik/27047_bmysher.txd" }
 MRP_MODELS[27048] = { base = 288, dff = "assets/kotnik/27048_bmyshersgt.dff", txd = "assets/kotnik/27048_bmyshersgt.txd" }
 MRP_MODELS[27049] = { base = 288, dff = "assets/kotnik/27049_bmyswt.dff", txd = "assets/kotnik/27049_bmyswt.txd" }
 MRP_MODELS[27050] = { base = 233, dff = "assets/kotnik/27050_wfybdu.dff", txd = "assets/kotnik/27050_wfybdu.txd" }
 MRP_MODELS[27051] = { base = 233, dff = "assets/kotnik/27051_wfyget.dff", txd = "assets/kotnik/27051_wfyget.txd" }
 MRP_MODELS[27052] = { base = 233, dff = "assets/kotnik/27052_wfysher.dff", txd = "assets/kotnik/27052_wfysher.txd" }
 MRP_MODELS[27053] = { base = 288, dff = "assets/kotnik/27053_wmybdu.dff", txd = "assets/kotnik/27053_wmybdu.txd" }
 MRP_MODELS[27054] = { base = 288, dff = "assets/kotnik/27054_wmyget.dff", txd = "assets/kotnik/27054_wmyget.txd" }
 MRP_MODELS[27055] = { base = 288, dff = "assets/kotnik/27055_wmysher.dff", txd = "assets/kotnik/27055_wmysher.txd" }
 MRP_MODELS[27056] = { base = 288, dff = "assets/kotnik/27056_wmysher2.dff", txd = "assets/kotnik/27056_wmysher2.txd" }
 MRP_MODELS[27057] = { base = 288, dff = "assets/kotnik/27057_wmyswt.dff", txd = "assets/kotnik/27057_wmyswt.txd" }
 MRP_MODELS[27060] = { base = 288, dff = "assets/kotnik/27060_boss.dff", txd = "assets/kotnik/27060_boss.txd" }
 MRP_MODELS[27061] = { base = 288, dff = "assets/kotnik/27061_dres.dff", txd = "assets/kotnik/27061_dres.txd" }
 MRP_MODELS[27062] = { base = 288, dff = "assets/kotnik/27062_forelli.dff", txd = "assets/kotnik/27062_forelli.txd" }
 MRP_MODELS[27063] = { base = 288, dff = "assets/kotnik/27063_heck1.dff", txd = "assets/kotnik/27063_heck1.txd" }
 MRP_MODELS[27066] = { base = 288, dff = "assets/kotnik/27066_skorka.dff", txd = "assets/kotnik/27066_skorka.txd" }
 MRP_MODELS[27067] = { base = 288, dff = "assets/kotnik/27067_staruch.dff", txd = "assets/kotnik/27067_staruch.txd" }
 MRP_MODELS[27068] = { base = 288, dff = "assets/kotnik/27068_swmori.dff", txd = "assets/kotnik/27068_swmori.txd" }
 MRP_MODELS[27069] = { base = 288, dff = "assets/kotnik/27069_swmyhp1.dff", txd = "assets/kotnik/27069_swmyhp1.txd" }
 MRP_MODELS[27071] = { base = 288, dff = "assets/kotnik/27071_vmaff12.dff", txd = "assets/kotnik/27071_vmaff12.txd" }
 MRP_MODELS[27073] = { base = 288, dff = "assets/kotnik/27073_vmaff22.dff", txd = "assets/kotnik/27073_vmaff22.txd" }
 MRP_MODELS[27075] = { base = 288, dff = "assets/kotnik/27075_vmaff33.dff", txd = "assets/kotnik/27075_vmaff33.txd" }
 MRP_MODELS[27077] = { base = 288, dff = "assets/kotnik/27077_vmaff44.dff", txd = "assets/kotnik/27077_vmaff44.txd" }
 MRP_MODELS[27078] = { base = 288, dff = "assets/kotnik/27078_wmori.dff", txd = "assets/kotnik/27078_wmori.txd" }
 MRP_MODELS[27079] = { base = 288, dff = "assets/kotnik/27079_wmygol2.dff", txd = "assets/kotnik/27079_wmygol2.txd" }
 MRP_MODELS[27080] = { base = 288, dff = "assets/kotnik/27080_zwyklak.dff", txd = "assets/kotnik/27080_zwyklak.txd" }
 MRP_MODELS[27081] = { base = 288, dff = "assets/kotnik/27081_dnb1.dff", txd = "assets/kotnik/27081_dnb1.txd" }
 MRP_MODELS[27082] = { base = 288, dff = "assets/kotnik/27082_dnb2.dff", txd = "assets/kotnik/27082_dnb2.txd" }
 MRP_MODELS[27083] = { base = 288, dff = "assets/kotnik/27083_dnb3.dff", txd = "assets/kotnik/27083_dnb3.txd" }
 MRP_MODELS[27084] = { base = 288, dff = "assets/kotnik/27084_somyst.dff", txd = "assets/kotnik/27084_somyst.txd" }
 MRP_MODELS[27085] = { base = 288, dff = "assets/kotnik/27085_triada.dff", txd = "assets/kotnik/27085_triada.txd" }
 MRP_MODELS[27086] = { base = 288, dff = "assets/kotnik/27086_triadb.dff", txd = "assets/kotnik/27086_triadb.txd" }
 MRP_MODELS[27087] = { base = 288, dff = "assets/kotnik/27087_triboss.dff", txd = "assets/kotnik/27087_triboss.txd" }
 MRP_MODELS[27094] = { base = 288, dff = "assets/kotnik/KKK.dff", txd = "assets/kotnik/KKK.txd" }
 MRP_MODELS[27095] = { base = 288, dff = "assets/kotnik/27095_bmyri.dff", txd = "assets/kotnik/27095_bmyri.txd" }
 MRP_MODELS[27096] = { base = 288, dff = "assets/kotnik/27096_bmyst.dff", txd = "assets/kotnik/27096_bmyst.txd" }
 MRP_MODELS[27097] = { base = 288, dff = "assets/kotnik/27097_ss.dff", txd = "assets/kotnik/27097_ss.txd" }
 MRP_MODELS[27098] = { base = 288, dff = "assets/kotnik/27098_vbmycr.dff", txd = "assets/kotnik/27098_vbmycr.txd" }
 MRP_MODELS[27099] = { base = 288, dff = "assets/kotnik/27099_wbdyg2.dff", txd = "assets/kotnik/27099_wbdyg2.txd" }
 MRP_MODELS[27100] = { base = 288, dff = "assets/kotnik/27100_wmybmx.dff", txd = "assets/kotnik/27100_wmybmx.txd" }
 MRP_MODELS[27101] = { base = 288, dff = "assets/kotnik/27101_wmydrug.dff", txd = "assets/kotnik/27101_wmydrug.txd" }
 MRP_MODELS[28001] = { base = 152, dff = "assets/kotnik/skin28001.dff", txd = "assets/kotnik/skin28001.txd" }
 MRP_MODELS[28002] = { base = 152, dff = "assets/kotnik/skin28002.dff", txd = "assets/kotnik/skin28002.txd" }
 MRP_MODELS[28003] = { base = 40, dff = "assets/kotnik/28003_neula.dff", txd = "assets/kotnik/28003_neula.txd" }
 MRP_MODELS[28004] = { base = 152, dff = "assets/kotnik/28004_neula2.dff", txd = "assets/kotnik/28004_neula2.txd" }
 MRP_MODELS[28005] = { base = 288, dff = "assets/kotnik/28005_dwayne.dff", txd = "assets/kotnik/28005_dwayne.txd" }
 MRP_MODELS[28006] = { base = 93, dff = "assets/kotnik/28006_pysio.dff", txd = "assets/kotnik/28006_pysio.txd" }
 MRP_MODELS[28007] = { base = 288, dff = "assets/kotnik/28007_spartacus.dff", txd = "assets/kotnik/28007_spartacus.txd" }
 MRP_MODELS[28008] = { base = 288, dff = "assets/kotnik/28008_shevey.dff", txd = "assets/kotnik/28008_shevey.txd" }
 MRP_MODELS[28009] = { base = 288, dff = "assets/kotnik/28009_pysio2.dff", txd = "assets/kotnik/28009_pysio2.txd" }
 MRP_MODELS[28010] = { base = 40, dff = "assets/kotnik/28010_sknatalia.dff", txd = "assets/kotnik/28010_sknatalia.txd" }
 MRP_MODELS[28011] = { base = 40, dff = "assets/kotnik/28011_sknatalia.dff", txd = "assets/kotnik/28011_sknatalia.txd" }
 MRP_MODELS[28012] = { base = 288, dff = "assets/kotnik/28012_metinek.dff", txd = "assets/kotnik/28012_metinek.txd" }
 MRP_MODELS[28013] = { base = 233, dff = "assets/kotnik/28013_stormi.dff", txd = "assets/kotnik/28013_stormi.txd" }
 MRP_MODELS[28014] = { base = 233, dff = "assets/kotnik/28014_aprilynne.dff", txd = "assets/kotnik/28014_aprilynne.txd" }
 MRP_MODELS[28015] = { base = 288, dff = "assets/kotnik/28015_personal.dff", txd = "assets/kotnik/28015_personal.txd" }
 MRP_MODELS[28016] = { base = 288, dff = "assets/kotnik/28016_personal.dff", txd = "assets/kotnik/28016_personal.txd" }
 MRP_MODELS[29002] = { base = 288, dff = "assets/kotnik/somyri.dff", txd = "assets/kotnik/somyri.txd" }
 MRP_MODELS[29003] = { base = 288, dff = "assets/kotnik/vla2.dff", txd = "assets/kotnik/vla2.txd" }
 MRP_MODELS[29004] = { base = 288, dff = "assets/kotnik/vmaff1.dff", txd = "assets/kotnik/vmaff1.txd" }
 MRP_MODELS[29005] = { base = 288, dff = "assets/kotnik/wfyst.dff", txd = "assets/kotnik/wfyst.txd" }
 MRP_MODELS[29006] = { base = 288, dff = "assets/kotnik/wmopj.dff", txd = "assets/kotnik/wmopj.txd" }
 MRP_OBJECT_MODELS[-2000] = { base = 19379, dff = "assets/kotnik/vape.dff", txd = "assets/kotnik/vape.txd", world = -1 }
 MRP_OBJECT_MODELS[-2001] = { base = 19379, dff = "assets/kotnik/gun_boxbig.dff", txd = "assets/kotnik/gun_boxbig.txd", world = -1 }
 MRP_OBJECT_MODELS[-2002] = { base = 19379, dff = "assets/kotnik/cellphone.dff", txd = "assets/kotnik/cellphone.txd", world = -1 }
 MRP_OBJECT_MODELS[-3001] = { base = 19379, dff = "assets/kotnik/hmm.dff", txd = "assets/kotnik/walls.txd", world = -1 }
 MRP_OBJECT_MODELS[-3002] = { base = 19379, dff = "assets/kotnik/sciana_waska.dff", txd = "assets/kotnik/walls.txd", world = -1 }
 MRP_OBJECT_MODELS[-3003] = { base = 19379, dff = "assets/kotnik/sciana.dff", txd = "assets/kotnik/walls.txd", world = -1 }
 MRP_OBJECT_MODELS[-3004] = { base = 19379, dff = "assets/kotnik/obramowka.dff", txd = "assets/kotnik/walls.txd", world = -1 }
 MRP_OBJECT_MODELS[-3005] = { base = 19379, dff = "assets/kotnik/pilar.dff", txd = "assets/kotnik/walls.txd", world = -1 }
 MRP_OBJECT_MODELS[-3006] = { base = 19379, dff = "assets/kotnik/sciana_mini_okno.dff", txd = "assets/kotnik/walls.txd", world = -1 }
 MRP_OBJECT_MODELS[-3007] = { base = 19379, dff = "assets/kotnik/podloga.dff", txd = "assets/kotnik/walls.txd", world = -1 }
 MRP_OBJECT_MODELS[-3008] = { base = 19379, dff = "assets/kotnik/sciana_waskie_drzwi.dff", txd = "assets/kotnik/walls.txd", world = -1 }
 MRP_OBJECT_MODELS[-3009] = { base = 19379, dff = "assets/kotnik/obramowka_waska.dff", txd = "assets/kotnik/walls.txd", world = -1 }
 MRP_OBJECT_MODELS[-3010] = { base = 19379, dff = "assets/kotnik/sciana_szerokie_drzwi.dff", txd = "assets/kotnik/walls.txd", world = -1 }
 MRP_OBJECT_MODELS[-3011] = { base = 19379, dff = "assets/kotnik/sciana_duze_okno.dff", txd = "assets/kotnik/walls.txd", world = -1 }
 MRP_OBJECT_MODELS[-3012] = { base = 19379, dff = "assets/kotnik/sciana_drzwi.dff", txd = "assets/kotnik/walls.txd", world = -1 }
 MRP_OBJECT_MODELS[-3013] = { base = 19379, dff = "assets/kotnik/podloga_mniejsza.dff", txd = "assets/kotnik/walls.txd", world = -1 }
 MRP_OBJECT_MODELS[-3014] = { base = 19379, dff = "assets/kotnik/sciana_zaokraglana.dff", txd = "assets/kotnik/walls.txd", world = -1 }
 MRP_OBJECT_MODELS[-3015] = { base = 19379, dff = "assets/kotnik/drabina.dff", txd = "assets/kotnik/walls.txd", world = -1 }
 MRP_OBJECT_MODELS[-3016] = { base = 19379, dff = "assets/kotnik/podloga_minimini.dff", txd = "assets/kotnik/walls.txd", world = -1 }
 MRP_OBJECT_MODELS[-3017] = { base = 19379, dff = "assets/kotnik/drzwi.dff", txd = "assets/kotnik/walls.txd", world = -1 }
 MRP_OBJECT_MODELS[-3018] = { base = 19379, dff = "assets/kotnik/wielka_sciana.dff", txd = "assets/kotnik/walls.txd", world = -1 }
 MRP_OBJECT_MODELS[-3019] = { base = 19379, dff = "assets/kotnik/ramy_drzwi.dff", txd = "assets/kotnik/walls.txd", world = -1 }
 MRP_OBJECT_MODELS[-2300] = { base = 19480, dff = "assets/kotnik/idlev2versiyon.dff", txd = "assets/kotnik/idlev2versiyon.txd", world = -1 }
 MRP_OBJECT_MODELS[-2301] = { base = 19480, dff = "assets/kotnik/idlev2pawnshop.dff", txd = "assets/kotnik/idlev2versiyon.txd", world = -1 }
 MRP_OBJECT_MODELS[-2303] = { base = 19480, dff = "assets/kotnik/idlev2liquer.dff", txd = "assets/kotnik/idlev2versiyon.txd", world = -1 }
 MRP_OBJECT_MODELS[-2302] = { base = 19480, dff = "assets/kotnik/idlepark.dff", txd = "assets/kotnik/idlepark.txd", world = -1 }
 MRP_OBJECT_MODELS[-2017] = { base = 19480, dff = "assets/kotnik/nwspltbild4_las2.dff", txd = "assets/kotnik/lashops93_las2.txd", world = -1 }
 MRP_OBJECT_MODELS[-2034] = { base = 19480, dff = "assets/kotnik/lae2_landhub02ff.dff", txd = "assets/kotnik/landhubpark.txd", world = -1 }
 MRP_OBJECT_MODELS[-2027] = { base = 19480, dff = "assets/kotnik/unionstwarc2_las.dff", txd = "assets/kotnik/railway_las.txd", world = -1 }
 MRP_OBJECT_MODELS[-2028] = { base = 19480, dff = "assets/kotnik/kotnik-market.dff", txd = "assets/kotnik/kotnik-market.txd", world = -1 }
 MRP_OBJECT_MODELS[-2029] = { base = 19480, dff = "assets/kotnik/gangshops4_lae2.dff", txd = "assets/kotnik/eastls1b_lae2.txd", world = -1 }
 MRP_OBJECT_MODELS[-2030] = { base = 19480, dff = "assets/kotnik/2030.dff", txd = "assets/kotnik/2030.txd", world = -1 }
 MRP_OBJECT_MODELS[-2031] = { base = 19480, dff = "assets/kotnik/2031.dff", txd = "assets/kotnik/2031.txd", world = -1 }
 MRP_OBJECT_MODELS[-2032] = { base = 19480, dff = "assets/kotnik/2032.dff", txd = "assets/kotnik/2032.txd", world = -1 }
 MRP_OBJECT_MODELS[-2033] = { base = 19480, dff = "assets/kotnik/2033.dff", txd = "assets/kotnik/2033.txd", world = -1 }
 MRP_OBJECT_MODELS[-2070] = { base = 19480, dff = "assets/kotnik/2070.dff", txd = "assets/kotnik/2070.txd", col = "assets/kotnik/2070.col", world = -1 }
 MRP_OBJECT_MODELS[-2071] = { base = 19480, dff = "assets/kotnik/2071.dff", txd = "assets/kotnik/2071.txd", col = "assets/kotnik/2071.col", world = -1 }
